name: Build mozc
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
      PKG_CONFIG_PATH: /opt/fcitx5/share/pkgconfig:/opt/fcitx5/lib/pkgconfig
      CMAKE_PREFIX_PATH: /opt/fcitx5
    steps:
      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get -y install \
            git \
            cmake \
            extra-cmake-modules \
            meson \
            ninja-build \
            libgtk-3-dev \
            libsystemd-dev \
            gcc g++ make \
            libwayland-dev \
            python-gi-dev \
            python3-all \
            wayland-protocols \
            wget curl \
            gettext
      - name: Build iso-codes
        run: |
          repo=https://salsa.debian.org/debian/iso-codes
          git clone --depth 1 -b $(git ls-remote --refs --tags $repo | cut -d / -f 3- | sort -V | tail -n 1) $repo
          (
            cd iso-codes
            meson setup --buildtype=release --prefix=/opt/fcitx5 build .
            sudo ninja -C build install
          )
      - name: Build json-c
        run: |
          repo=https://github.com/json-c/json-c.git
          git clone --depth 1 -b $(git ls-remote --refs --tags $repo | cut -d / -f 3- | sort -V | tail -n 1) $repo
          (
            mkdir json-c/build
            cd json-c/build
            cmake -GNinja .. \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=/opt/fcitx5 \
              -DBUILD_APPS=OFF \
              -DBUILD_SHARED_LIBS=OFF \
              -DBUILD_STATIC_LIBS=ON \
              -DBUILD_TESTING=OFF
            sudo ninja install
          )
      - name: Build fmt
        run: |
          last_tag=$(curl -s https://api.github.com/repos/fmtlib/fmt/releases/latest | grep -oP '(?<=tag_name": ").*(?=")')
          git clone --depth 1 -b $last_tag https://github.com/fmtlib/fmt.git
          (
            mkdir fmt/build
            cd fmt/build
            cmake -GNinja .. \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=/opt/fcitx5 \
              -DFMT_DOC=OFF \
              -DFMT_TEST=OFF
            sudo ninja install
          )
      - name: Build fcitx5
        run: |
          repo=https://github.com/fcitx/fcitx5.git
          git clone --depth 1 -b $(git ls-remote --refs --tags $repo | cut -d / -f 3- | sort -V | tail -n 1) $repo
          (
            mkdir fcitx5/build
            cd fcitx5/build
            cmake -GNinja .. \
              -DBUILD_SPELL_DICT=OFF \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=/opt/fcitx5 \
              -DENABLE_ENCHANT=OFF \
              -DENABLE_TEST=OFF \
              -DENABLE_X11=OFF \
              -DENABLE_XDGAUTOSTART=OFF
            sudo ninja install
          )
      - name: Build mozc
        run: |
          repo=https://github.com/bazelbuild/bazelisk.git
          curl -L -o /tmp/bazelisk https://github.com/bazelbuild/bazelisk/releases/download/$(git ls-remote --tags --refs $repo | cut -d / -f 3- | sort -V | tail -n 1)/bazelisk-linux-amd64
          chmod +x /tmp/bazelisk

          git clone --depth 1 --recursive https://github.com/fcitx/mozc
          patch mozc/src/config.bzl <<- 'EOF'
          	@@ -40,5 +40,5 @@ BAZEL_TOOLS_PREFIX = "@bazel_tools"
          	 LINUX_MOZC_BROWSER_COMMAND = "/usr/bin/xdg-open"
          	-LINUX_MOZC_ICONS_DIR = "/usr/share/icons/mozc"
          	-LINUX_MOZC_SERVER_DIR = "/usr/lib/mozc"
          	-LINUX_MOZC_DOCUMENT_DIR = LINUX_MOZC_SERVER_DIR + "/documents"
          	+LINUX_MOZC_ICONS_DIR = "/opt/fcitx5/share/icons/mozc"
          	+LINUX_MOZC_SERVER_DIR = "/opt/fcitx5/bin"
          	+LINUX_MOZC_DOCUMENT_DIR = "/opt/fcitx5/share/doc"
          	 IBUS_COMPONENT_DIR = "/usr/share/ibus/component"
          	EOF

          cd mozc/src
          /tmp/bazelisk build \
            -c opt \
            --copt=-fPIC \
            --copt=-DNDEBUG \
            --config oss_linux \
            --nostart_end_lib \
            --linkopt=-Wl,-rpath,/opt/fcitx5/lib \
            --linkopt=-L/opt/fcitx5/lib \
            unix/fcitx5:fcitx5-mozc.so \
            server:mozc_server

          PREFIX=/opt/fcitx5 bash ../scripts/install_fcitx5_bazel
          install -m 755 bazel-bin/server/mozc_server /opt/fcitx5/bin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fcitx5-mozc
          path: /opt/fcitx5

#        working-directory: fcitx5
